-- DDL

DROP TABLE IF EXISTS shop CASCADE;
DROP TABLE IF EXISTS parent CASCADE;
DROP TABLE IF EXISTS lesson CASCADE;
DROP TABLE IF EXISTS reservation CASCADE;

CREATE TABLE shop
(
    id                bigint generated by default as identity,
    shop_name         varchar(100) not null,
    address           varchar(255) not null,
    created_date_time DATETIME     not null,
    updated_date_time DATETIME     not null,
    primary key (id)
);

CREATE TABLE parent
(
    id                bigint generated by default as identity,
    parent_name       varchar(50)  not null,
    email             varchar(255) not null,
    created_date_time DATETIME     not null,
    updated_date_time DATETIME     not null,
    primary key (id)
);

CREATE TABLE lesson
(
    id                bigint generated by default as identity,
    shop_id           bigint             not null,
    lesson_name       varchar(100)       not null,
    lesson_limit      integer default 20 not null,
    current_limit     integer default 20  not null,
    version           bigint  default 0  not null,
    date              DATE               not null,
    created_date_time DATETIME           not null,
    updated_date_time DATETIME           not null,
    primary key (id)
);

CREATE TABLE reservation
(
    id                 bigint generated by default as identity,
    lesson_id          bigint      not null,
    parent_id          bigint      not null,
    count              integer     not null,
    reservation_status varchar(50) not null,
    created_date_time  DATETIME    not null,
    updated_date_time  DATETIME    not null,
    primary key (id)
);

-- lesson 테이블에 shop_id 외래 키 추가
ALTER TABLE lesson
    ADD CONSTRAINT fk_shop_id
        FOREIGN KEY (shop_id)
            REFERENCES shop (id);

-- reservation 테이블에 lesson_id 외래 키 추가
ALTER TABLE reservation
    ADD CONSTRAINT fk_lesson_id
        FOREIGN KEY (lesson_id)
            REFERENCES lesson (id);

-- reservation 테이블에 parent_id 외래 키 추가
ALTER TABLE reservation
    ADD CONSTRAINT fk_parent_id
        FOREIGN KEY (parent_id)
            REFERENCES parent (id);


-- DML

INSERT INTO shop (shop_name, address, created_date_time, updated_date_time)
VALUES ('잠실', '서울시 송파구', NOW(), NOW()),
       ('일산', '경기도 일산시', NOW(), NOW()),
       ('판교', '경기도 성남시', NOW(), NOW());

INSERT INTO parent (parent_name, email, created_date_time, updated_date_time)
VALUES ('권나라', 'parent1@gmail.com', NOW(), NOW()),
       ('아이유', 'parent2@gmail.com', NOW(), NOW()),
       ('최민식', 'parent3@gmail.com', NOW(), NOW()),
       ('코카코', 'parent4@gmail.com', NOW(), NOW()),
       ('이이이', 'parent5@gmail.com', NOW(), NOW());

INSERT INTO lesson (shop_id, lesson_name, date, created_date_time, updated_date_time)
VALUES (1, '도시농부', '2024-03-05', NOW(), NOW()),
       (2, '도시농부', '2024-03-05', NOW(), NOW()),
       (3, '도시농부', '2024-03-05', NOW(), NOW()),
       (1, '도시농부', '2024-03-06', NOW(), NOW()),
       (2, '도시농부', '2024-03-06', NOW(), NOW()),
       (3, '도시농부', '2024-03-06', NOW(), NOW()),
       (1, '도시농부', '2024-03-07', NOW(), NOW()),
       (2, '도시농부', '2024-03-07', NOW(), NOW()),
       (3, '도시농부', '2024-03-07', NOW(), NOW()),
       (1, '도시농부', '2024-03-08', NOW(), NOW()),
       (2, '도시농부', '2024-03-08', NOW(), NOW()),
       (3, '도시농부', '2024-03-08', NOW(), NOW()),
       (1, '도시농부', '2024-03-09', NOW(), NOW()),
       (2, '도시농부', '2024-03-09', NOW(), NOW()),
       (3, '도시농부', '2024-03-09', NOW(), NOW());

INSERT INTO lesson (shop_id, lesson_name, date, created_date_time, updated_date_time)
VALUES (1, '드로잉', '2024-03-10', NOW(), NOW()),
       (2, '드로잉', '2024-03-10', NOW(), NOW()),
       (3, '드로잉', '2024-03-10', NOW(), NOW()),
       (1, '드로잉', '2024-03-11', NOW(), NOW()),
       (2, '드로잉', '2024-03-11', NOW(), NOW()),
       (3, '드로잉', '2024-03-11', NOW(), NOW()),
       (1, '드로잉', '2024-03-12', NOW(), NOW()),
       (2, '드로잉', '2024-03-12', NOW(), NOW()),
       (3, '드로잉', '2024-03-12', NOW(), NOW()),
       (1, '드로잉', '2024-03-13', NOW(), NOW()),
       (2, '드로잉', '2024-03-13', NOW(), NOW()),
       (3, '드로잉', '2024-03-13', NOW(), NOW()),
       (1, '드로잉', '2024-03-14', NOW(), NOW()),
       (2, '드로잉', '2024-03-14', NOW(), NOW()),
       (3, '드로잉', '2024-03-14', NOW(), NOW()),
       (1, '드로잉', '2024-03-15', NOW(), NOW()),
       (2, '드로잉', '2024-03-15', NOW(), NOW()),
       (3, '드로잉', '2024-03-15', NOW(), NOW());

INSERT INTO lesson (shop_id, lesson_name, date, created_date_time, updated_date_time)
VALUES (1, '오감놀이', '2024-03-16', NOW(), NOW()),
       (2, '오감놀이', '2024-03-16', NOW(), NOW()),
       (3, '오감놀이', '2024-03-16', NOW(), NOW()),
       (1, '오감놀이', '2024-03-17', NOW(), NOW()),
       (2, '오감놀이', '2024-03-17', NOW(), NOW()),
       (3, '오감놀이', '2024-03-17', NOW(), NOW()),
       (1, '오감놀이', '2024-03-18', NOW(), NOW()),
       (2, '오감놀이', '2024-03-18', NOW(), NOW()),
       (3, '오감놀이', '2024-03-18', NOW(), NOW()),
       (1, '오감놀이', '2024-03-19', NOW(), NOW()),
       (2, '오감놀이', '2024-03-19', NOW(), NOW()),
       (3, '오감놀이', '2024-03-19', NOW(), NOW());


